[package]
name = "delryn"
version.workspace = true
edition.workspace = true

[dependencies]
delryn-model = { workspace = true }
delryn-infra = { workspace = true }
delryn-store = { workspace = true }
anyhow.workspace = true
arboard.workspace = true
crossterm.workspace = true
ego-tree.workspace = true
epub.workspace = true
html2text.workspace = true
image.workspace = true
lru.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
regex.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
syntect.workspace = true
toml.workspace = true
ureq.workspace = true
zip.workspace = true
