[package]
name = "delryn-format"
version.workspace = true
edition.workspace = true

[dependencies]
delryn-model = { workspace = true }
anyhow.workspace = true
ego-tree.workspace = true
epub.workspace = true
html2text.workspace = true
image.workspace = true
pdfium-render.workspace = true
regex.workspace = true
scraper.workspace = true
zip.workspace = true
